export default {
      technos : [
          'React js',
          'Php',
          'Symfony',
          'Go',
          'Python',
          'Java',
          'VueJs',
          'Laravel',
          'Wordpress',
          'Magento',
          'C#',
          'C++',
          'Zend',
          'Node Js',
          'Express',
          'SQL',
          'Angular',
          'ASP',
          'CSS',
          'Tailwind CSS',
          'Bootstrap',
          'JQuery',
          'Javascript',
          'Ruby',
          'Swift',
          'React Native',
          'Spring',
          'Flutter',
          'Ionic',
          'Django',
          'Backbone js',
          'Mongo DB',
          'PostgreSQL',
          'Zend',
          'Test',
          'TDD',
          'AWS',
      ],
      token: localStorage.getItem('user-token') || '',
      userAuth: localStorage.getItem('user-email') || '',
      userId: localStorage.getItem('userId') || '',
      thisUser : {}
      //mentorId: localStorage.getItem('mentor-id') ,
      //oneMentor : JSON.parse(localStorage.getItem('oneMentor')) 
};